# Generated by Django 4.1 on 2022-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='author',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='pages',
        ),
        migrations.AddField(
            model_name='grocery',
            name='quantiles',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocery',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
