# Generated by Django 4.1 on 2022-08-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_author_grocery_brand_remove_grocery_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='quantiles',
            new_name='qualities',
        ),
    ]
