# Generated by Django 4.1 on 2022-08-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_qualities_grocery_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='author',
        ),
    ]
