# Generated by Django 4.1 on 2022-08-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_grocery_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='qualities',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
